### ISSUE TITLE
Connecting with all Security None to opcplc 2.5.0 running in EFLOW VM form host system fails

### ISSUE THREAD

**Issue by martin-weber** [Azure-Samples/iot-edge-opc-plc#178]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Run OPpcPlc 2.5.0 in EFLOW with the following settings:

```json
   "opcplc1": {
        "settings": {
            "image": "localhost:5500/opc-plc:2.5.0",
            "createOptions": {
                "Hostname": "opcplc1",
                "Cmd": [
                    "--sph",
                    "--aa",
                    "--unsecuretransport",
                    "--fr=1",
                    "--sr=2",
                    "--ph=opcplc1",
                    "--to"
                ],
                "ExposedPorts": {
                    "50000/tcp": {},
                    "8080/tcp": {}
                },
                "HostConfig": {
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Target": "/appdata",
                            "Source": "opcplc1",
                            "Consistency": "consistent",
                            "RW": true
                        }
                    ],
                    "PortBindings": {
                        "50000/tcp": [
                            {
                                "HostPort": "50000"
                            }
                        ],
                        "8080/tcp": [
                            {
                                "HostPort": "8080"
                            }
                        ]
                    }
                }
            }
        },
        "env": {
            "BypassCertVerification": {
                "value": "true"
            },
            "AutoAcceptUntrustedCertificates": {
                "value": "true"
            }
        },
        "type": "docker",
        "version": "1.0",
        "status": "running",
        "restartPolicy": "always",
        "startupOrder": 2
    },
```

Get the EFLOW-VM IP-Address
```powerhsell
Get-EflowVmAddr

 - Virtual machine IP : 172.27.71.63 retrieved directly from virtual machine
```

Use an OPC UA Client such as Softing dataFEED OPC UA Client:
Endpoint URL: opc.tcp://172.27.71.63:50000
Security Mode: None
Secuity Policy: None
Message Encoding: Binary

Try to connect from the client with the settings above fails with error:

### Any log messages given by the failure
Error in Client:
```text
2022-10-06 19:36:17.729 [17], TraceMask:Error, Message: BadCertificateHostNameInvalid ObjectId: SessionConnectViewModel BadCertificateHostNameInvalid 'BadCertificateHostNameInvalid'
2022-10-06 19:36:17.729 [17], TraceMask:Error, Message: ClientSession.InternalConnect - Session Connect error  BadCertificateHostNameInvalid 'BadCertificateHostNameInvalid'
```

docker logs opcplc1 in EFLOW VM:
```text
[17:36:16 ERR] OPC: Certificate rejected. Reason=CN=OpcPlc. [CN=OpcPlc] [BB1A26C8C5CFC4A348A660D70478107CCE9ACE47]
[17:36:16 ERR] OPC: 10/06/2022 17:36:16.487 Certificate rejected. Reason=Opc.Ua.ServiceResultException: The domain '172.27.71.63' is not listed in the server certificate.. [CN=OpcPlc] [BB1A26C8C5CFC4A348A660D70478107CCE9ACE47]
[17:36:16 ERR] OPC: Server - SESSION CREATE failed. The domain '172.27.71.63' is not listed in the server certificate.
[17:36:16 ERR] OPC: 10/06/2022 17:36:16.488 Server - SESSION CREATE failed. The domain '172.27.71.63' is not listed in the server certificate.
[17:36:16 ERR] OPC: SERVER - Service Fault Occurred. Reason=BadCertificateHostNameInvalid
[17:36:16 ERR] OPC: 10/06/2022 17:36:16.488 SERVER - Service Fault Occurred. Reason=BadCertificateHostNameInvalid
[17:36:16 ERR] OPC: Certificate rejected. Reason=CN=OpcPlc. [CN=OpcPlc] [BB1A26C8C5CFC4A348A660D70478107CCE9ACE47]
[17:36:16 ERR] OPC: 10/06/2022 17:36:16.490 Certificate rejected. Reason=Opc.Ua.ServiceResultException: The domain '172.27.71.63' is not listed in the server certificate.. [CN=OpcPlc] [BB1A26C8C5CFC4A348A660D70478107CCE9ACE47]
[17:36:16 ERR] OPC: Server - SESSION CREATE failed. The domain '172.27.71.63' is not listed in the server certificate.
[17:36:16 ERR] OPC: 10/06/2022 17:36:16.493 Server - SESSION CREATE failed. The domain '172.27.71.63' is not listed in the server certificate.
[17:36:16 ERR] OPC: SERVER - Service Fault Occurred. Reason=BadCertificateHostNameInvalid
[17:36:16 ERR] OPC: 10/06/2022 17:36:16.494 SERVER - Service Fault Occurred. Reason=BadCertificateHostNameInvalid
```

### Expected/desired behavior

With Opc-Plc 2.2.0 the and the exact same deployment template a connection with None/None form outside works.
Therefore I expect that it would work the same with version 2.5.0 as with 2.2.0.

### OS and Version?
> Windows 11 and EFLOW 1.3.0

### Versions
iotedge version 1.3.0 or 1.4.0 tested
opcplc 2.5.0

### Mention any other details that might be useful

* Connection with none inside the VM works.
* Connecting using SignAndEncrypt from Host to opcplc 2.5.0 in VM works as well.

**Comment by luiscantero** [comment]
@martin-weber you specified the option `--ph=opcplc1` to set the hostname accordingly, yet you connect using the IP address `opc.tcp://172.27.71.63:50000`. You should be able to connect either A) using the hostname in the URI, and also B) using the IP address after removing the option `--ph=...`.

I discussed the issue briefly and we think that the change in behavior is probably due to a security concern that was solved in one of the newer OPC UA SDK.

**Comment by luiscantero** [comment]
@martin-weber please try v2.5.1, thanks.

**Comment by martin-weber** [comment]
@luiscantero I tried the with 2.5.1 after removing the `--ph=...`. I still get the following errors, when connecting to `opc.tcp://172.30.66.232:50000` (EFLOW VM IP) form the host:
```
[18:19:45 ERR] OPC: Certificate rejected. Reason=CN=OpcPlc. [CN=OpcPlc] [9D14904FC99CC3C5AA480D9D5BBA2B033E4C35AB]
[18:19:45 ERR] OPC: 10/17/2022 18:19:45.638 Certificate rejected. Reason=Opc.Ua.ServiceResultException: The domain '172.30.66.232' is not listed in the server certificate.. [CN=OpcPlc] [9D14904FC99CC3C5AA480D9D5BBA2B033E4C35AB]
[18:19:45 ERR] OPC: Server - SESSION CREATE failed. The domain '172.30.66.232' is not listed in the server certificate.
[18:19:45 ERR] OPC: 10/17/2022 18:19:45.639 Server - SESSION CREATE failed. The domain '172.30.66.232' is not listed in the server certificate.
[18:19:45 ERR] OPC: SERVER - Service Fault Occurred. Reason=BadCertificateHostNameInvalid
[18:19:45 ERR] OPC: 10/17/2022 18:19:45.639 SERVER - Service Fault Occurred. Reason=BadCertificateHostNameInvalid
[18:19:45 ERR] OPC: Certificate rejected. Reason=CN=OpcPlc. [CN=OpcPlc] [9D14904FC99CC3C5AA480D9D5BBA2B033E4C35AB]
[18:19:45 ERR] OPC: 10/17/2022 18:19:45.641 Certificate rejected. Reason=Opc.Ua.ServiceResultException: The domain '172.30.66.232' is not listed in the server certificate.. [CN=OpcPlc] [9D14904FC99CC3C5AA480D9D5BBA2B033E4C35AB]
[18:19:45 ERR] OPC: Server - SESSION CREATE failed. The domain '172.30.66.232' is not listed in the server certificate.
[18:19:45 ERR] OPC: 10/17/2022 18:19:45.641 Server - SESSION CREATE failed. The domain '172.30.66.232' is not listed in the server certificate.
[18:19:45 ERR] OPC: SERVER - Service Fault Occurred. Reason=BadCertificateHostNameInvalid
[18:19:45 ERR] OPC: 10/17/2022 18:19:45.641 SERVER - Service Fault Occurred. Reason=BadCertificateHostNameInvalid
```

**Comment by luiscantero** [comment]
Add feature #181

**Comment by luiscantero** [comment]
Fixed with the new option `--cdn`.
